### ISSUE TITLE
vcpkg does not have telnet server include files

### ISSUE THREAD

**Issue by tukotech** [daniele77/cli#104]
First  off, thanks for the library.

Looking at Github and what's installed as part of vcpkg shows that telnet server support is not included in vcpkg. May request for updated package with telnet support?

**Comment by daniele77** [comment]
Hi @tukotech . First of all, thank you for using the library.

I checked and it seems to me that `vcpkg` works fine. In particular, I see that it installs all the `cli` header files, included `remotecli.h` (that provides telnet server support). On my machine I can find all header files in the path: `<vcpkg>/packages/cli_x64-linux/include/cli/`.

Can you enumerate the steps you took? What are you expecting and what you got instead?

Please, let me know.

**Comment by daniele77** [comment]
@tukotech since I didn't receive any other feedback, in a couple of days I will close this issue.
Please, let me know if you solved your issue.

**Comment by tukotech** [comment]
Apologies for not responding sooner. 

Upon looking more closely, I have realized that I used the sample code from the master branch while using vcpkg package which was based off of tag v1.2.1. The sample code for v1.2.1 is a little different.

**Comment by tukotech** [comment]
OK, I have verified that I was using sample code from master and v1.2.1 version of vcpkg. Closing this ticket - thanks for investigating.
