### ISSUE TITLE
Add support for packaging using conan

### ISSUE THREAD

**Issue by rob-baily** [daniele77/cli#113]
Have been working with conan as a package manager and I like it!  I think it would be useful to have this in Conan Center under https://conan.io/center/.   To do this there is information at https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md which is the repo where the recipe goes.  I've created a simple recipe that works for me.  I will create a pull request so it can be reviewed and I will cross reference with this for any discussion.

**Comment by daniele77** [comment]
Hey, @rob-baily thank you very much for your contribution!
We already have support for `vcpkg` package manager and adding `conan` support has been on my TODO list since ever. Unfortunately, I don't know enough conan to add a new library so your help is welcome! I'll have a look at your PR in the next few days.

**Comment by rob-baily** [comment]
I've been working it a bit lately so it is fresh so happy to help.   Once we are happy with the publishing from the project itself we can see how to get it into conan center.  Have not done that before so it will be interesting to see how that works.

**Comment by daniele77** [comment]
@rob-baily I did some research about submitting new open source libraries to Conan Center Index.
This is what I understood :-)

1. The library author (i.e., me) must request access to the Early Access Program by writing a comment in a specific Conan Center Index GitHub issue.
2. Fork the `conan-center-index` github repository
3. Create a new folder `cli` with subfolders for each version containing its recipe (i.e., the file `conanfile.py`) and `test_package`
4. submit a PR to  `conan-center-index` 

right?
So... if I understood correctly, I should use the `conanfile.py` of your PR for the PR to `conan-center-index `repository, do you agree? `cli `repository does not need the file `conanfile.py`, does it?

**Comment by rob-baily** [comment]
@daniele77 This sounds basically right.  I think the conanfile.py should work as it gets the source from the GitHub release tag.  It does not support multiple versions for now but that is probably OK.  I did not create anything for the test_package but that should be simple.  Normally this a library to link but with header only project that is not a part of it.

The cli project does not need it but it might be nice when making any changes to be able to try it out.  The form in the cli project would be different as it would reference the source locally.  Its your call as to whether you want to include it in the cli project.

**Comment by rob-baily** [comment]
@daniele77 Found out something else that is strange.  Compiling the examples with the standard process worked when just using the out of the box compile flags but when adding cli to my own project I needed to set to C++14 per 
https://docs.conan.io/en/latest/howtos/manage_cpp_standard.html.  Since cli requires C++14 I am not sure how it works without this.  Not sure if it is any issue but something to keep in mind for now.

**Comment by rob-baily** [comment]
Cancel that last comment.  The cli CMakeLists.txt contains this `target_compile_features(cli INTERFACE cxx_std_14)` so that is of course why it works for that.  Since I did not explicitly include it in my cmake config I needed it to be activated by conan.  They have a discussion in conan on this topic here https://github.com/conan-io/conan/issues/7772 and https://github.com/conan-io/conan/issues/6157

**Comment by daniele77** [comment]
@rob-baily I think we should wait to submit the Conan PR after we release `cli` v. 2.0 (I hope this would happen very soon).
v. 2.0 will bring important changes (e.g., break API, work with standalone `asio` library, work without dependencies if no telnet server is needed, etc. -- you can have a hint by looking at the git head source) above all on its dependencies, so a dependency manager like Conan will be largely impacted.
What do you think about it?

**Comment by rob-baily** [comment]
Seems reasonable to me although I don't know if there is any downside in putting the current version up there.  At some level it might be good to try it now with the current version since we think we have a working file and go through the process with Conan center so that 2.0 is easier.  But its your call and either way seems fine.

Did not try using HEAD but I can take a look to see how that might work.

**Comment by rob-baily** [comment]
@daniele77 I had move on from the project that was using this previously but I am back on a new project where I plan to use your great library! 

I have created a conan packaging setup locally which seems to work at I created https://github.com/conan-io/conan-center-index/issues/22564 to get it added there which I will do after I get access.   

I will close the PR that I opened a while ago for this and we can leave this open until the package is in Conan Center and then you or I can update the README to indicate the support.

**Comment by daniele77** [comment]
That's fantastic, @rob-baily.
Thank you very much. Could you check when the package will be available in Conan Center and then update the README yourself?
Please let me know, it would be very beneficial to have the library available on Conan!

**Comment by rob-baily** [comment]
@daniele77 It took some time for me to get access.  Now I have it and started a draft PR.  Could you please review the conanfile.py file under this https://github.com/conan-io/conan-center-index/pull/22673/files and confirm that the descriptive items between lines 8 and 13 make sense?

When that PR is done I will submit a PR here with the link to the appropriate Conan Center location.

**Comment by daniele77** [comment]
In the conanfile.py the lines between 8 and 13 are:

    name = "cli"
    description = "A library for interactive command line interfaces in modern C++"
    license = "BSL-1.0"
    url = "https://github.com/conan-io/conan-center-index"
    homepage = "https://github.com/daniele77/cli"
    topics = "cli-interface", "cpp14", "no-dependencies", "cli", "header-only"
    
 Everything seems right to me.

**Comment by rob-baily** [comment]
@daniele77 Could you please take a look at this comment https://github.com/conan-io/conan-center-index/pull/22673#issuecomment-1934583228 and respond to how the library works in regards to Boost?  The change being suggested in the Conan recipe is that you can specify the Boost option when declaring the dependency to CLI and then Boost would be included in the dependencies.  Not sure if you have anything like this for the other package managers you have this set up for.

**Comment by daniele77** [comment]
Just added this comment:
https://github.com/conan-io/conan-center-index/pull/22673#issuecomment-1939217903
hope this help.

**Comment by rob-baily** [comment]
@daniele77 Just add PR #225 for the documentation and added some spelling corrections.  Please see what you think.

**Comment by daniele77** [comment]
@rob-baily building with Conan works nicely.
Thank you very much for your effort to reach this result.
