### ISSUE TITLE
Backspace is not working in MobaXterm

### ISSUE THREAD

**Issue by paulsubrata55** [daniele77/cli#122]
In putty the backspace int value is 127 but in MobaXterm (https://mobaxterm.mobatek.net/) the value is 8. Hence, the cli apps are not usable in MobaXterm.

**Comment by daniele77** [comment]
Thank you very much for reporting this issue.
We're going to insert this in the roadmap.

**Comment by daniele77** [comment]
Just to be sure: are you starting the app inside MobaXterm, right?
I.e., you're not using the remote cli server and MobaXterm as a telnet client, but the standalone cli application from MobaXterm.

**Comment by daniele77** [comment]
Could you please check if the issue you're facing is related to the issue #123 ?
(or if the #123 is the right solution for the MobaXterm problem?)

**Comment by paulsubrata55** [comment]
> starting the app inside MobaXterm

**Comment by paulsubrata55** [comment]
> Just to be sure: are you starting the app inside MobaXterm, right?
> I.e., you're not using the remote cli server and MobaXterm as a telnet client, but the standalone cli application from MobaXterm.

Yes, I am starting the app inside MobaXterm. No telnet.

**Comment by daniele77** [comment]
O, I guess the right solution (to take into account every possible terminal and key code) should be the one described in issue #123
