### ISSUE TITLE
Bug instantiating Local terminal sessions in multiple threads

### ISSUE THREAD

**Issue by kalowery** [daniele77/cli#132]
### Discussed in https://github.com/daniele77/cli/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **kalowery** October 23, 2021</sup>
Hi - I'm using cli and really like it.  It's going to save me huge amounts of time. I'm working on a tool that presents a cli on different threads at different times in a multi-threaded application. There's a segfault bug in linuxkeyboard.h when doing this. It has to do with the detached thread reading keyboard input (i.e. std::getchar) which is still alive after tearing down the session (it's blocking in getchar). The next time the user presses a key the detached thread returns from getchar (in Read()) but the reference to the scheduler is now invalid and the call to Post crashes with a segfault because the vtable is gone.

I got it to quit crashing by having LinuxKeyboard check the "run" boolean member variable before calling notify.  It still eats the first key stroke that would have gone to a new local session instance, which is annoying but it's better than crashing. I'm using the LoopScheduler and calling Stop() in my ExitAction. I'm open to the idea that I'm tearing things down improperly, but I really think it's an artifact of the detached thread being stuck in a blocking call to getchar() when the session is torn down. </div>

**Comment by kalowery** [comment]
This was a little more challenging to reproduce than I had hoped. The issue is (I believe) that the references held by the linuxkeyboard thread, though "destroyed", are still hanging around on the stack. Anyway, this reproduces the crash but I was only able to reproduce it by creating at least 1 cli instance in a separate thread.  Just keep exiting out of cli instances and it will crash on the third exit.

This code can be compiled by:
g++ -pthread -I .. clibug.cc -o clibug


#include <cli/include/cli/cli.h>
#include <cli/include/cli/clilocalsession.h>
#include <cli/include/cli/loopscheduler.h>
#include <string.h>
#include <thread>

using namespace cli;
using namespace std;


class myScheduler : public LoopScheduler
{
public:
    myScheduler() : LoopScheduler()
    {
    }
    ~myScheduler()
    {
        std::cout << "Deleting scheduler";
    }
};

void cliThread()
{
    LoopScheduler scheduler2;
    std::unique_ptr<Menu> rootMenu;
    rootMenu = make_unique<Menu> ("cliBug2");
    rootMenu -> Insert(
            "bugtest",
            [](std::ostream& out){ out << "Test this bug"; },
            "Type \"exit\" to teardown this cli and start another one" );
    Cli cli2(std::move(rootMenu));
    CliLocalTerminalSession session2(cli2,scheduler2,std::cout);
    cli2.ExitAction( [&](auto& out){out << "Exiting -- goodbye\n"; scheduler2.Stop();});
    scheduler2.Run();
}

int main (int argc, char **argv)
{
    char buff[10000];
    {
        std::unique_ptr<Menu> rootMenu;
        rootMenu = make_unique<Menu> ("cliBug");
        rootMenu -> Insert(
                "bugtest",
                [](std::ostream& out){ out << "Test this bug"; },
                "Type \"exit\" to teardown this cli and start another one" );
        LoopScheduler *scheduler = new(buff) LoopScheduler();
        Cli cli(std::move(rootMenu));
        CliLocalTerminalSession session(cli,*scheduler,std::cout);
        cli.ExitAction( [&](auto& out){out << "Exiting -- goodbye\n"; scheduler->Stop();});
        scheduler->Run();
        scheduler = NULL;
    }
    std::thread t1(cliThread);
    t1.join();
    {
        memset(reinterpret_cast<void *>(buff), 0, sizeof(buff));
        LoopScheduler scheduler2;
        std::unique_ptr<Menu> rootMenu;
        rootMenu = make_unique<Menu> ("cliBug");
        rootMenu -> Insert(
                "bugtest",
                [](std::ostream& out){ out << "Test this bug"; },
                "Type \"exit\" to teardown this cli and start another one" );
        Cli cli2(std::move(rootMenu));
        CliLocalTerminalSession session2(cli2,scheduler2,std::cout);
        cli2.ExitAction( [&](auto& out){out << "Exiting -- goodbye\n"; scheduler2.Stop();});
        scheduler2.Run();
    }
}

**Comment by kalowery** [comment]
FYI - This approach to LinuxKeyboard::Read() works pretty well for never blocking in std::getchar.  The issue revolves entirely around deleting the LinuxKeyboard object out from under the servant thread.  I also have ~LinuxKeyboard sleep for 1 second prior to returning. This guarantees that the servant thread is terminated prior to the LinuxKeyboard instance becoming invalid. These values can be reduced to whatever granularity is appropriate for the application. 

  void Read()
    {
        while ( run )
        {
           fd_set rfds;
           struct timeval tv;
           int retval;

            /* Watch stdin (fd 0) to see when it has input. */
            FD_ZERO(&rfds);
            FD_SET(0, &rfds);
            /* Wait up to .5 seconds. */
            tv.tv_sec = 0;
            tv.tv_usec = 500000;

            retval = select(1, &rfds, NULL, NULL, &tv);
            if (retval > 0 && run)
            {
                auto k = Get();
                Notify(k);
            }
        }
    }

**Comment by daniele77** [comment]
This is the minimal code reproducing the bug (linux):

```
#include <cli/cli.h>
#include <cli/clilocalsession.h>
#include <cli/loopscheduler.h>
#include <string.h>
#include <thread>

using namespace cli;
using namespace std;

void cliThread()
{
    LoopScheduler scheduler2;
    auto rootMenu = make_unique<Menu> ("cliBug1");
    Cli cli2(std::move(rootMenu));
    CliLocalTerminalSession session2(cli2,scheduler2,std::cout);
    cli2.ExitAction( [&](auto& out){out << "Exiting -- goodbye\n"; scheduler2.Stop();});
    scheduler2.Run();
}

int main ()
{
#if 1 // segfault
    cliThread();
#else
    {
        LoopScheduler scheduler2;
        auto rootMenu = make_unique<Menu> ("cliBug2");
        Cli cli2(std::move(rootMenu));
        CliLocalTerminalSession session2(cli2,scheduler2,std::cout);
        cli2.ExitAction( [&](auto& out){out << "Exiting -- goodbye\n"; scheduler2.Stop();});
        scheduler2.Run();
    }
#endif
    LoopScheduler scheduler2;
    auto rootMenu = make_unique<Menu> ("cliBug2");
    Cli cli2(std::move(rootMenu));
    CliLocalTerminalSession session2(cli2,scheduler2,std::cout);
    cli2.ExitAction( [&](auto& out){out << "Exiting -- goodbye\n"; scheduler2.Stop();});
    scheduler2.Run();

    return 0;
}
```

The problem can be solved by using a non-blocking `std::getchar` in `LinuxKeyboard `and checking for the flag run.

However, the same issue can arise in `WinKeyboard `too.
