### ISSUE TITLE
Conflicting namespaces with aff3ct

### ISSUE THREAD

**Issue by h-sh-h** [daniele77/cli#167]
Hi and Thanks for the great library.

In the process of compiling a program which uses both cli library and aff3ct library. I got namespace conflict error.
Both libraries define "rang" namespace which leads to multiple definition error.

How can i fix it ?

Thanks

**Comment by h-sh-h** [comment]
I just fix it by making namespace rang a sub-namespace of cli.

**Comment by daniele77** [comment]
Yes, however, it should be fixed in the code of cli.
I'm going to fix that on the next commit.
