### ISSUE TITLE
Feature EnterAction

### ISSUE THREAD

**Issue by Dup4** [daniele77/cli#177]
We can register a function to `ExitAction()` to do some of the things we want to do when the session exits

So correspondingly, can we add an `EnterAction()` hook to do something we want to do when the session is first entered?

For example, output a welcome message, a help message, etc.

**Comment by Dup4** [comment]
If this feature is approved, I can try to help implement it.

**Comment by daniele77** [comment]
Ok, I think it might be useful. If you want, send a PR.

**Comment by Dup4** [comment]
ok, I can try to send a PR

**Comment by daniele77** [comment]
Thank you very much for your help.
