### ISSUE TITLE
find_package(cli) doesn't define cli_VERSION

### ISSUE THREAD

**Issue by yurivict** [daniele77/cli#192]
Most cmake-based packages do define ```{name}_VERSION```.

**Comment by daniele77** [comment]
Right. Could you provide a PR for that?

**Comment by daniele77** [comment]
@yurivict cli library already define `cli_VERSION` variable and you can read it when find_package is used (i.e., with conan package manager).
On the other hand, cmake does not allow a project to read variables defined in libraries added using `add_subdirectory`, so in that case unfortunately you cannot have that information.
