### ISSUE TITLE
Text pasted from the clipboard doesn'r get into the cli prompt

### ISSUE THREAD

**Issue by yurivict** [daniele77/cli#200]
How to reproduce:
1. Select some text in the terminal
2. Press Ctrl-Shift-C to copy it
3. Enter the cli prompt
4. Press Ctrl-Shift-V to paste it
5. Only the first letter is pasted, and the rest is not

Version: 2.0.2
Terminal: xfce4
FreeBSD 13.2

**Comment by daniele77** [comment]
Thank you for the comment.
I think this issue has already been solved (see  #185 )
Can you check please the last commit of the repo, please?
