### ISSUE TITLE
Prompt label access

### ISSUE THREAD

**Issue by guestieng** [daniele77/cli#203]
A little but handy **feature request**: 
making it possible to allow for a change of the command prompt label after initialization.
All that would be needed, 
was to, e.g., make **public** the members **Cli::RootMenu()** and **Menu::prompt**, with the latter being made **non-const**, of course.
This change would, e.g., allow for displaying different "states" in the prompt label, such as a logging-plus-input mode or distinguished sub-cli's in general.

**Comment by guestieng** [comment]
Yes, indeed, this seems to be the case.

**Comment by daniele77** [comment]
Ok, I'm gonna close this issue and keep #199 
It's already planned.
