### ISSUE TITLE
Add vcpkg support

### ISSUE THREAD

**Issue by gocarlos** [daniele77/cli#23]
Would be great to use this library with cmake/vcpkg

**Comment by daniele77** [comment]
I don’t know (yet) Vcpkg, but it could be convenientl @gocarlos could you help me with this? Anyone else?

**Comment by goeddek** [comment]
Hello, we try to use this cli in our upcomming server, so we started to play around with it. I already did some vcpkg packaging (but I am by far no expert) and packeged some libraries at work. So if you are still looking for somebody, i will give it a try :-)

**Comment by gocarlos** [comment]
easiest thing to start, would be to add cmake to this repo, as cmake is the default for vcpkg and the defacto standard for c++

**Comment by daniele77** [comment]
A reddit user wrote just now he would do a pull request for cmake support.
Then @goeddek could work on the vcpkg, if he’s so kind to contribute.
I guess we should span a new branch for this work.

**Comment by SuperWig** [comment]
The PR has been merged so I guess you can close this now.
