### ISSUE TITLE
[feature request ]move from submenu to parent menu functionality

### ISSUE THREAD

**Issue by redboltz** [daniele77/cli#233]
When I am in submenu, I sometimes want to back to the parent menu.  In order to to that, I need to type the parent menu name.

If a special command to move up to the parent menu exists, it nice.
For example `..` (like a directory model).

I think that if the command tree has 3 or more level submenu, eg. `root -> sub -> subsub -> subsubsub`, `..` (one level up) is very convenient.

**Comment by daniele77** [comment]
You're right: it's not so natural have to use the parent menu name.
I definitely consider plan the development of this feature.
Thanks.

**Comment by daniele77** [comment]
As you can notice, it works with autocompletion, too!
