### ISSUE TITLE
assyncsession not supported on Windows

### ISSUE THREAD

**Issue by SuperWig** [daniele77/cli#33]
(and any other non-posix OS) Due to this line
https://github.com/daniele77/cli/blob/master/cli/cliasyncsession.h#L90

Could possibly give a diagnostic?
```cpp
#if _WIN32
#error "Currently not supported. #issue"
#endif
//or
#if !__has_include(<unistd.h>)
#error "Currently not supported. #issue"
#endif
```
Of the compilers on Godbolt that support C++14 but not __has_include are gcc 4.9.0 and 4.9.1
Edit: 🤦‍♂️ just realised that Boost has several macros to be able to test for this...

**Comment by daniele77** [comment]
Closed with f91756b34f24bde5c08b96beb48a87ba64153706.
