### ISSUE TITLE
Build fails...

### ISSUE THREAD

**Issue by p1v0t** [daniele77/cli#40]
Boost Version: 1.70.0
OS: Debian GNU/Linux 9 (stretch) 64-bit / Gnome Version 3.22.2
Error Message: 
```
/home/adem/LibSrc/cli/include/cli/remotecli.h:446:28: error: ‘boost::asio::ip::tcp::socket {aka class boost::asio::basic_stream_socket<boost::asio::ip::tcp>}’ has no member named ‘get_io_service’
         InputDevice(socket.get_io_service()),
                            ^~~~~~~~~~~~~~
examples/CMakeFiles/complete.dir/build.make:62: recipe for target 'examples/CMakeFiles/complete.dir/complete.cpp.o' failed
```

**Comment by daniele77** [comment]
Thank you.
The problem is due to the fact that the method `get_io_service()` has been removed from boost asio v. 1.70.
The line:
`socket.get_io_service()`
should be changed to:
`socket.get_executor().context()`
I'm gonna fix it as soon as possible.

**Comment by sdebionne** [comment]
Hi @daniele77, is there any chance to get a release with this fix, say v1.1.1?

**Comment by daniele77** [comment]
@sdebionne Done. Release 1.1.1 is available. It also fixes other issues.

**Comment by sdebionne** [comment]
Thank you very much!
