### ISSUE TITLE
Bind to specific address

### ISSUE THREAD

**Issue by vrobles-gee** [daniele77/cli#44]
Hello. I really like your library, thanks for it. I'm confident it will get better as more functionalities are added.

I am actually using it on an new project, but I am facing the following issue: I need to bind the telnet server to a single address for security reasons. I was checking the source code, but I think that currently it cann't be controlled when creating a CliTelnetServer instance. It seems to listen in all available interfaces by default, am I right?

[https://github.com/daniele77/cli/blob/master/include/cli/server.h#L126](https://github.com/daniele77/cli/blob/master/include/cli/server.h#L126)

If that's the case, can we add a constructor that will allow the developer to specify the IP address he wants the server to listen to? I am willing to help with this PR.

Thanks.

**Comment by daniele77** [comment]
Hi @vrobles-gee,
I agree that it's a useful feature.
It would be great if you could issue a PR with a new constructor that takes the IP address where listen to.
Your contribution is welcome!

**Comment by vrobles-gee** [comment]
Hi Daniele,

Great. I will send a PR for your review when is done.

Thanks,

**Comment by vrobles-gee** [comment]
I noticed PR was already merged into master and will close the issue. Thank you.
