### ISSUE TITLE
Backspace from remote terminal

### ISSUE THREAD

**Issue by sdebionne** [daniele77/cli#51]
It looks like backspace may not be properly handled (at least on Windows with the Windows telnet client). With a debugger I can see `'\b'` in the strings that are matched to commands or arguments. Backspace is properly echoed though. Might be an issue with the telnet client and its configuration.

**Comment by daniele77** [comment]
Thank you @sdebionne .
I tried: with putty the backspace works fine. On the other hand, with the telnet client, I experimented the same problem.
However, the general issue with the window client is already been pointed out in issue #19
