### ISSUE TITLE
Avoid duplicated commands on history

### ISSUE THREAD

**Issue by vrobles-gee** [daniele77/cli#55]
Hello. I would like to ask if there is a way to avoid storing the same command over and over on history. If it is not possible right now, can you please provide some hint on the relevant classes/functions to modify to make it work? I will be willing to add it and send a PR. Thanks.

**Comment by daniele77** [comment]
Hi @vrobles-gee , thank you for this hint: it's very relevant.

My initial idea was to copy the bash history behavior.
In particular, a command should not be stored in history if the *previous* is identical. I.e. the sequence of commands: A B B A A should result in the history content: A B A.

This is the behavior of bash history, and it's the only behavior I will consider as a PR.

If you'd like to contribute, my suggestion is to start adding the relevant test in the file `test/test_history.cpp`, and only then change the behavior in the file `include/cli/history.h`

**Comment by vrobles-gee** [comment]
Hi @daniele77. Thanks for your fast response. Yes, actually the bash history behavior is the one I want too. Thanks for pointing to the relevant files. I will send you a PR for this next week.

**Comment by daniele77** [comment]
@vrobles-gee great: your contribution is welcome.
I think bash is the user experience we're all accustomed to, so we should aim at it as a model.
I ask you to write the relevant tests, to help my evaluation of the PR.
Thank you again.

**Comment by vrobles-gee** [comment]
Hi @daniele77, I just opened #56 for this. Related test is included. Please let me know if any changes are required. Thanks.
