### ISSUE TITLE
Is there a way to get help for arugements 

### ISSUE THREAD

**Issue by vmudhire12** [daniele77/cli#80]
HI All, 
Is there any way to get help for arguments. 
Lets say, I want to pass arg1 and arg2. 
For example:  command -> add <arg1>  <arg2>
In this case, I am looking for when tab after tab, 
It should say, enter arg1 and then it say enter arg2

Would appreciate if some help me here

**Comment by daniele77** [comment]
If you're asking whether is it possible to have help about command arguments using the TAB key, unfortunately, the answer is no because TAB is used for autocompletion (and not for help).
However, it's planned to add TAB autocompletion for arguments, instead (see issues #68 and #69).
