### ISSUE TITLE
Auto complete and history in 'simplelocalsession' example

### ISSUE THREAD

**Issue by ptrdtznr** [daniele77/cli#83]
Hello,
I am pretty new to this lib, but I was missing an example of how to extend the *simplelocalsession.cpp* example with an auto-complete and a history.  Is it even possible?! I would like to avoid the boost dependcy.

thanks in advance!

**Comment by daniele77** [comment]
Currently, `CliFileSession ` session (used in the `simplelocalsession.cpp` example) does not need `boost` libraries but does not provide all the features (i.e., autocompletion, history, and -- in general -- everything that requires handling of keyboard "special" keys).

On the other hand, `CliLocalTerminalSession `  (used in the `complete.cpp` example) provides all the features but does need `boost `libraries.

I'm currently working to remove boost dependencies from `CliFileSession`, too, but I'm having some issues with the concurrency model to adopt. I hope to release a new version soon.

**Comment by ptrdtznr** [comment]
Okay! If you check my fork https://github.com/ptrdtznr/cli is based on connorjak, who forked your repo. He was able to make it run, but somehow under Ubuntu it was not working. I have made few changes but a "ctrl-c" is not working proper.

**Comment by daniele77** [comment]
@ptrdtznr , on the master branch of the repository you can find the most updated library:
- it can use standalone `asio ` or `boost asio` to provide remote sessions
- it does not depend on any third-party library if you don't need remote sessions
- copy and paste works, as usual, both on windows and linux.
So, I can say that connorjak fork is obsolete, now and this issue can be closed.
An official release is planned in a couple of weeks.
