### ISSUE TITLE
how to keep output and input at the same time?

### ISSUE THREAD

**Issue by dotkt** [daniele77/cli#86]
hi i love your project it is very nice.
i wonder how to keep output some str and receive user's input command at the same time?
![图片](https://user-images.githubusercontent.com/49758966/101276977-c82a7500-37eb-11eb-94c2-e82fa5e63d7f.png)

i hope user trigger some logic by cli's menu or submenu, cli will work perfect,
but when cli is traping in user's logic,i also want to use cli  to tell myfunc to stop do the work 
how to do it ?
sorry about my poor English,not  my mother language

**Comment by daniele77** [comment]
Hi @dotkt 
first of all, thank you for using my library.
If you like it, you can support the project in one of the following ways:
- spreading the word (let's reach 1000 stars!!! :-) )
- become a sponsor by clicking on the button with the heart on top of this page: even a symbolic amount can motivate a lot working on a side project like this!

---

Now the answer to your question.
If I've understood correctly, you need to start and stop some kind of "long elaboration" by using the CLI and -- maybe -- interact with the elaboration during the run.
You can do it in several ways, I can give you an example here, by using a class that has the responsibility of the elaboration, the concurrency model, the synchronization:

    class MyLongTask
    {
      public:
        MyLongTask()
        { 
            running.test_and_set();
        }
        void Start(std::ostream& out, int x, int y, int z)
        {
            th = make_unique<std::thread>(
                [=, &out]() // please note that x, y and z are copied because they're allocated in the stack and are short lived
                {
                    while(running.test_and_set())
                    {
                        this_thread::sleep_for(chrono::milliseconds(1000));
                        out << "Sum result = " << x+y+z << endl;
                    }
                }
            );
        }
        void Stop()
        {
            running.clear();
        }
    private:
        unique_ptr<std::thread> th;
        atomic_flag running = ATOMIC_FLAG_INIT; // I'm using an atomic flag here, but you can use a std::mtx instead
    };
    
    int main()
    {
        ...
        MyLongTask task;
        auto rootMenu = make_unique< Menu >( "cli" );
        rootMenu->Insert(
                "start",
                [&task](std::ostream& out, int x, int y, int z){ task.Start(out, x, y, z); },
                "Start my long task" );
        rootMenu->Insert(
                "stop",
                [&task](std::ostream& /*out*/){ task.Stop(); },
                "Stop my long task" );
        ....

---

Please note that your example uses the variables `x`, `y` and `z` by reference long after they've been destroyed: this will provoke almost certainly a crash.

**Comment by dotkt** [comment]
thank you very much it's very kind of you
