### ISSUE TITLE
Remove the symbol `BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT`

### ISSUE THREAD

**Issue by daniele77** [daniele77/cli#89]
Remove the symbol `BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT` since it can ripple up in the user code.

small question, is a fundamental fix in the pipeline, instead of this define, since that can ripple up, to user code which does not want this define to switch the boost asio back to the past ?

_Originally posted by @killerbot242 in https://github.com/daniele77/cli/issues/79#issuecomment-715582716_

**Comment by killerbot242** [comment]
I can confirm the issue is fixed
